AWSTemplateFormatVersion: "2010-09-09"
Description: Tick streams
Parameters:
  ParamName:
    Type: String
Resources:
  IngestStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub '${ParamName}-ingest'
      RetentionPeriodHours: 24
      ShardCount: 1
  # VwapStream:
  #   Type: AWS::Kinesis::Stream
  #   Properties:
  #     Name: !Sub '${ParamName}-vwap'
  #     RetentionPeriodHours: 24
  #     ShardCount: 1
  # TickAnalytics:
  #   Type: AWS::KinesisAnalytics::Application
  #   Properties:
  #     ApplicationName: !Sub '${ParamName}-analytics'
  #     ApplicationDescription: 'Application for calculating VWAP'
  #     Inputs:
  #       - KinesisStreamsInput:
  #           ResourceARN !GetAtt IngestStream.Arn
  #           RoleARN:
Outputs:
  OutIngestPhysicalId:
    Value: !Ref IngestStream
  OutIngestArn:
    Value: !GetAtt IngestStream.Arn
  # OutVwapPhysicalId:
  #   Value: !Ref VwapStream
  # OutVwapArn:
  #   Value: !GetAtt VwapStream.Arn
  # OutAnalytics:
  #   Value: !Ref TickAnalytics
