AWSTemplateFormatVersion: "2010-09-09"
Description: Tick streams
Parameters:
  name:
    Type: String
  shardCount:
    Type: Number
Resources:
  Ingest:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub '${name}-ingest'
      RetentionPeriodHours: 24
      ShardCount: !Ref shardCount
  # Vwap:
  #   Type: AWS::Kinesis::Stream
  #   Properties:
  #     Name: !Sub '${name}-vwap'
  #     RetentionPeriodHours: 24
  #     ShardCount: 1
  # Analytics:
  #   Type: AWS::KinesisAnalytics::Application
  #   Properties:
  #     ApplicationName: !Sub '${name}-analytics'
  #     ApplicationDescription: 'Application for calculating VWAP'
  #     Inputs:
  #       - KinesisStreamsInput:
  #           ResourceARN !GetAtt Ingest.Arn
  #           RoleARN:
  Consumer:
    Type: AWS::Kinesis::StreamConsumer
    Properties:
      ConsumerName: !Sub '${name}-consumer'
      StreamARN: !GetAtt Ingest.Arn
Outputs:
  outIngestPhysicalId:
    Value: !Ref Ingest
  outIngestArn:
    Value: !GetAtt Ingest.Arn
  # outVwapPhysicalId:
  #   Value: !Ref Vwap
  # outVwapArn:
  #   Value: !GetAtt Vwap.Arn
  # outAnalytics:
  #   Value: !Ref Analytics
  outConsumer:
    Value: !Ref Consumer
