AWSTemplateFormatVersion: "2010-09-09"
Description: Tick Kinesis data streams
Parameters:
  pName:
    Type: String
  pShardCount:
    Type: Number
Resources:
  Ingest:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub '${pName}-ingest'
      RetentionPeriodHours: 24
      ShardCount: !Ref pShardCount
  # Vwap:
  #   Type: AWS::Kinesis::Stream
  #   Properties:
  #     Name: !Sub '${pName}-vwap'
  #     RetentionPeriodHours: 24
  #     ShardCount: 1
  # Analytics:
  #   Type: AWS::KinesisAnalytics::Application
  #   Properties:
  #     ApplicationName: !Sub '${pName}-analytics'
  #     ApplicationDescription: 'Application for calculating VWAP'
  #     Inputs:
  #       - KinesisStreamsInput:
  #           ResourceARN !GetAtt Ingest.Arn
  #           RoleARN:
  # Consumer1:
  #   Type: AWS::Kinesis::StreamConsumer
  #   Properties:
  #     ConsumerName: !Sub '${pName}-consumer-1'
  #     StreamARN: !GetAtt Ingest.Arn
  # Consumer2:
  #   Type: AWS::Kinesis::StreamConsumer
  #   Properties:
  #     ConsumerName: !Sub '${pName}-consumer-2'
  #     StreamARN: !GetAtt Ingest.Arn
Outputs:
  outIngest:
    Value: !Ref Ingest
  outIngestArn:
    Value: !GetAtt Ingest.Arn
  # outVwap:
  #   Value: !Ref Vwap
  # outVwapArn:
  #   Value: !GetAtt Vwap.Arn
  # outAnalytics:
  #   Value: !Ref Analytics
  # outConsumer1:
  #   Value: !Ref Consumer1
  # outConsumer2:
  #   Value: !Ref Consumer2
